http:
  port: ${HTTP_PORT}
admin:
  port: ${ADMIN_PORT}
  host: ${ADMIN_HOST}
apiEndpoints:
  api:
    host: ${API_HOST}
    paths: '/ip'
  authorizerWithRole:
    host: ${AUTHORIZER_HOST}
    paths: ['/authentication/users/firebase-token']
  authorizer:
    host: ${AUTHORIZER_HOST}
    paths: ['/authentication/*']
  customerProfileEscort:
    host: ${CUSTOMER_PROFILE_HOST}
    paths: ['/customer/:id/profile/avatar', '/customer/:id/profile/photos']
  customerProfile:
    host: ${CUSTOMER_PROFILE_HOST}
    paths: ['/customer/*']
  escortProfileCustomer:
    host: ${ESCORT_PROFILE_HOST}
    paths:
      - /escort/:id/profile/attention-sites
      - /escort/:id/profile/avatar
      - /escort/:id/profile/photos
      - /escort/:id/profile/prices
      - /escort/:id/profile
      - /escort/:id/profile/schedules
      - /escort/:id/profile/service
      - /escort/:id/profile/biography
    methods:
      - GET
  escortProfile:
    host: ${ESCORT_PROFILE_HOST}
    paths:
      - /escort/profile/*
      - /escort/profile
      - /escort/attention-site-categories
      - /escort/days
      - /escort/identification-parts
      - /escort/nationalities
      - /escort/profile-status-categories
      - /escort/service-categories
      - /escort/time-categories
  payment:
    host: ${PAYMENT_HOST}
    paths: ['/payments/*']
  claimWithRole:
    host: ${CLAIM_HOST}
    paths: ['/claims/:id/dictum']
  claim:
    host: ${CLAIM_HOST}
    paths: ['/claims', '/claims/*']
  tracking:
    host: ${TRACKING_HOST}
    paths: ['/tracking/*']
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  authorizerService:
    url: ${AUTHORIZER_URL}
  customerProfileService:
    url: ${CUSTOMER_PROFILE_URL}
  escortProfileService:
    url: ${ESCORT_PROFILE_URL}
  paymentService:
    url: ${PAYMENT_URL}
  claimService:
    url: ${CLAIM_URL}
  trackingService:
    url: ${TRACKING_URL}
policies:
  - log
  - proxy
  - jwt
  - request-transformer
  - auth
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  authorizerWithRolePipeline:
    apiEndpoints:
      - authorizerWithRole
    policies:
      - jwt:
          - action:
              secretOrPublicKey: ${SECRET_KEY}
              checkCredentialExistence: false
      - request-transformer:
          - action:
              headers:
                add:
                  user-id: req.user.id
          - action:
              headers:
                add:
                  user-type: req.user.type
      - auth:
          - action:
              roles: Escort,Customer
              valueKey: header
  authorizerPipeline:
    apiEndpoints:
      - authorizer
    policies:
      - proxy:
          - action:
              serviceEndpoint: authorizerService 
              changeOrigin: true
  customerProfileEscortPipeline:
    apiEndpoints:
      - customerProfileEscort
    policies:
      - jwt:
          - action:
              secretOrPublicKey: ${SECRET_KEY}
              checkCredentialExistence: false
      - request-transformer:
          - action:
              headers:
                add:
                  user-id: req.user.id
          - action:
              headers:
                add:
                  user-type: req.user.type
          - action:
              headers:
                add:
                  firebase-token: req.user.firebaseToken
      - auth:
          - action:
              roles: Escort
              valueKey: header
              mandatoryRole: Customer
  customerProfilePipeline:
    apiEndpoints:
      - customerProfile
    policies:
      - jwt:
          - action:
              secretOrPublicKey: ${SECRET_KEY}
              checkCredentialExistence: false
      - request-transformer:
          - action:
              headers:
                add:
                  user-id: req.user.id
          - action:
              headers:
                add:
                  user-type: req.user.type
          - action:
              headers:
                add:
                  firebase-token: req.user.firebaseToken
      - proxy:
          - action:
              serviceEndpoint: customerProfileService
              changeOrigin: true
  escortProfileCustomerPipeline:
    apiEndpoints:
      - escortProfileCustomer
    policies:
      - jwt:
          - action:
              secretOrPublicKey: ${SECRET_KEY}
              checkCredentialExistence: false
      - request-transformer:
          - action:
              headers:
                add:
                  user-id: req.user.id
          - action:
              headers:
                add:
                  user-type: req.user.type
          - action:
              headers:
                add:
                  firebase-token: req.user.firebaseToken
      - auth:
          - action:
              roles: Customer
              valueKey: header
              mandatoryRole: Escort
      - proxy:
          - action:
              serviceEndpoint: escortProfileService
              changeOrigin: true
  escortProfilePipeline:
    apiEndpoints:
      - escortProfile
    policies:
      - jwt:
          - action:
              secretOrPublicKey: ${SECRET_KEY}
              checkCredentialExistence: false
      - request-transformer:
          - action:
              headers:
                add:
                  user-id: req.user.id
          - action:
              headers:
                add:
                  user-type: req.user.type
          - action:
              headers:
                add:
                  firebase-token: req.user.firebaseToken
      - auth:
          - action:
              roles: Escort
              valueKey: header
              mandatoryRole: Escort
      - proxy:
          - action:
              serviceEndpoint: escortProfileService
              changeOrigin: true
  paymentPipeline:
    apiEndpoints:
      - payment
    policies:
      - jwt:
          - action:
              secretOrPublicKey: ${SECRET_KEY}
              checkCredentialExistence: false
      - request-transformer:
          - action:
              body:
                add:
                  user: req.user
      - proxy:
          - action:
              serviceEndpoint: paymentService
              changeOrigin: true
  claimWithRolePipeline:
      apiEndpoints:
        - claimWithRole
      policies:
        - jwt:
            - action:
                secretOrPublicKey: ${SECRET_KEY}
                checkCredentialExistence: false
        - request-transformer:
            - action:
                headers:
                  add:
                    user-id: req.user.id
            - action:
                headers:
                  add:
                    user-type: req.user.type
            - action:
                headers:
                  add:
                    firebase-token: req.user.firebaseToken
        - auth:
            - action:
                roles: User
                valueKey: header
  claimPipeline:
      apiEndpoints:
        - claim
      policies:
        - jwt:
            - action:
                secretOrPublicKey: ${SECRET_KEY}
                checkCredentialExistence: false
        - request-transformer:
            - action:
                headers:
                  add:
                    user-id: req.user.id
            - action:
                headers:
                  add:
                    user-type: req.user.type
            - action:
                headers:
                  add:
                    firebase-token: req.user.firebaseToken
        - proxy:
            - action:
                serviceEndpoint: claimService
                changeOrigin: true
  trackingPipeline:
      apiEndpoints:
        - tracking
      policies:
        - jwt:
            - action:
                secretOrPublicKey: ${SECRET_KEY}
                checkCredentialExistence: false
        - request-transformer:
            - action:
                headers:
                  add:
                    user-id: req.user.id
            - action:
                headers:
                  add:
                    user-type: req.user.type
            - action:
                headers:
                  add:
                    firebase-token: req.user.firebaseToken
        - proxy:
            - action:
                serviceEndpoint: trackingService
                changeOrigin: true
