http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  authorizer:
    host: localhost
    paths: ['/authentication/*']
  profile:
    host: localhost
    paths: ['/customer/profile/*']
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  authorizerService:
    url: 'http://localhost:3000/api/v1'
  profileService:
    url: 'http://localhost:5002/api/v1'
policies:
  - log
  - proxy
  - jwt
  - request-transformer
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  authorizerPipeline:
    apiEndpoints:
      - authorizer
    policies:
      - proxy:
          - action:
              serviceEndpoint: authorizerService 
              changeOrigin: true
  profilePipeline:
    apiEndpoints:
      - profile
    policies:
      - jwt:
          - action:
              secretOrPublicKey: ''
              checkCredentialExistence: false
      - request-transformer:
          - action:
              body:
                add:
                  user: req.user
      - proxy:
          - action:
              serviceEndpoint: profileService
              changeOrigin: true
